### ISSUE TITLE
Does not support spring data elasticsearch?

### ISSUE THREAD

**Issue by taoqianlilang** [nshou/elasticsearch-kibana#12]
Does this support spring data elastic search? It seems that 9300 port is needed, but you do not give

**Comment by nshou** [comment]
Currently, the port 9300 is not published on purpose for simplicity. This image is aiming to provide the opportunity to explore what ES and Kibana are like quickly so it is intended to run as a single node. Still, I'm positively thinking to change this policy if there are lots of requests.
