### ISSUE TITLE
 warning: usage of JAVA_HOME is deprecated, use ES_JAVA_HOME

### ISSUE THREAD

**Issue by VolckaertAchiel** [nshou/elasticsearch-kibana#17]
i got this when i launched the container...

**Comment by txj-xyz** [comment]
This is completely fixed by using `ES_JAVA_HOME` instead of `JAVA_HOME`

However, this message is only a warning.

The only reason I haven't made a pull request for this is due to untested repercussions

**Comment by txj-xyz** [comment]
See https://github.com/nshou/elasticsearch-kibana/pull/18 for a fix to this.

**Comment by txj-xyz** [comment]
@VolckaertAchiel

**Comment by nshou** [comment]
I'm sorry @VolckaertAchiel I completely overlooked this. And, thank you so much @txj-xyz always for the fix. I'm looking at it now.
