### ISSUE TITLE
Update stack to 8.x.x

### ISSUE THREAD

**Issue by txj-xyz** [nshou/elasticsearch-kibana#20]
Any plans to update this further?

This works really well for our development environments.

**Comment by txj-xyz** [comment]
@nshou

**Comment by nshou** [comment]
Thank you @txj-xyz. I've been less motivated since they have changed their licensing policy since 7.11, but let me check it out now again

**Comment by txj-xyz** [comment]
Thanks, would be awesome if we could setup single-node with kibana + elastic on 8.x for dev (actually using in prod for ephemeral instances)

**Comment by nshou** [comment]
Since 8.x.x, they stopped shipping no-jdk bundle so I'll need to switch the release bundles and base docker image. I don't think it'd take long. Meanwhile, the upgrade to the latest change in 7.x.x was straightforward so I did it first for now.

**Comment by nshou** [comment]
8566a5e256de7f94f28fa155a4e2a5c987a6efdc will enable 8.7.1. The images on docker hub are being uploaded now.

**Comment by txj-xyz** [comment]
Lol, all 56 of our testing environments decided to update today and this image does not have an enrollment token provided to it out of the box, so I had to setup enrollment tokens and passwords 56 times.

**Comment by txj-xyz** [comment]
This image does not work out of the box anymore, please revert if possible.

**Comment by txj-xyz** [comment]
I fixed this, it was a me issue
