### ISSUE TITLE
Additional Memory allocation

### ISSUE THREAD

**Issue by txj-xyz** [nshou/elasticsearch-kibana#21]
Support for additional Memory to JVM feature?

**Comment by nshou** [comment]
Hi @txj-xyz. What do you mean by that? A feature to pass -xmx or -xms env vars to elasticsearc?

**Comment by txj-xyz** [comment]
I will close this tomorrow, I realized JVM arguments can be passed via
Elastic ENV

**Comment by nshou** [comment]
Thank you for reporting it. When you have a chance, I'm wondering you could share the idea of what you wanted and how you fulfilled it as I'm interested in it. I'm guessing you passed something like ES_JAVA_OPTS="-Xms16g -Xmx16g" somehow.

**Comment by txj-xyz** [comment]
I used ES_JAVA_OPTS correct, use your imahe as a base image and add an ENV
field, mostly looking to base your image and make a small kubernetes
container with this for our onsite deployments

**Comment by txj-xyz** [comment]
Sorry, that is currently what its used for but yeah just a nice starting
spot
