### ISSUE TITLE
The version of Elasticsearch on Dockerhub is still 7.16

### ISSUE THREAD

**Issue by Starsoul233** [nshou/elasticsearch-kibana#22]
Hi there, I just pull the latest image from dockerhub. Although the description shows ES version is 8.7 ,the ES inside is still 7.16

**Comment by nshou** [comment]
Hi @Starsoul233, thank you for reporting. Just now I tried downloading the latest image and I was able to confirm it was 8.7.1. What was the exact command you tried? I did: `$ docker run -d -p 9200:9200 nshou/elasticsearch-kibana` then `$ curl localhost:9200`.

Possibly you have an old image on cache. What does the output of the following command look like? `$ docker images --digests`. You should see a line like "nshou/elasticsearch-kibaba    latest    sha256:548a8b4fe8dce835488311921ffed1c74be9c3f042c60feab08b22d75c250d20". If the digest differs, you should probably need to `$ docker pull nshou/elasticsearch-kibana:latest` agian to get the newer image.

**Comment by Starsoul233** [comment]
Hi nshou, I've tried to pull the image again with the command you wrote. It shows the images is updated 21 months ago. 
![image](https://github.com/nshou/elasticsearch-kibana/assets/58240139/b8d73fb9-15f1-4f02-91a1-81fadff9fc7b)

**Comment by Starsoul233** [comment]
this is how docker images --digests shows. 
![image](https://github.com/nshou/elasticsearch-kibana/assets/58240139/52d6d724-fe73-4878-96b1-3350718f96e8)

**Comment by nshou** [comment]
Strange. What happens if you remove the image on local with `docker rmi` (not `rm`) and `docker pull` it again?

**Comment by txj-xyz** [comment]
@nshou Can you push the new `latest` build to docker?

**Comment by nshou** [comment]
Done.

This repository used to be auto-synced to dockerhub by dockerhub's feature when new code is pushed, uploading the latest images and updating README, etc on dockerhub. However, recently docker has changed the pricing policy and the feature is no longer available for free users (yes it's me :). As such, I deleted that automation part. If you know the other way to achieve the same thing, it'd be super welcome.

**Comment by txj-xyz** [comment]
Looks like there is not a workaround to that. This is probably NIT to close now :)
