### ISSUE TITLE
support for passing a custom password

### ISSUE THREAD

**Issue by dkezri** [nshou/elasticsearch-kibana#25]
is there any way to pass a custom password for elastic instead of running   elastic_reset_password?

**Comment by txj-xyz** [comment]
Currently at the moment the `elastic-reset-password` tool will handle making the system user password at start up, you cannot pass a username/password into the main system user for Elasticsearch.

Once the `elastic` user password has been changed you can make multiple other users after its booted.

**Comment by dkezri** [comment]
Done !

**Comment by txj-xyz** [comment]
Awesome stuff!
